name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          - hashmap
          - btreemap

    steps:
    - uses: actions/checkout@v3
    
    - name: Build with ${{ matrix.features }} features
      run: cargo build --verbose --features ${{ matrix.features }}

    - name: Run tests with ${{ matrix.features }} features
      run: cargo test --verbose --features ${{ matrix.features }}
